# Generated by Django 4.2.24 on 2025-09-26 22:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Имя датчика может содержать только русские и латинские буквы, цифры, тире и слеш', regex='^[а-яА-Яa-zA-Z0-9\\-/]+$')])),
                ('type', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'db_table': 'Датчики',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Название события может содержать только русские и латинские буквы, цифры, _,  и N/A.', regex='^([а-яА-Яa-zA-Z0-9_]+|N/A)?$')])),
                ('temperature', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(5499.0)])),
                ('humidity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'db_table': 'События',
                'indexes': [models.Index(fields=['created_at'], name='События_created_46e565_idx'), models.Index(fields=['sensor_id'], name='События_sensor__e13a92_idx'), models.Index(fields=['sensor_id', 'created_at'], name='События_sensor__b703d7_idx'), models.Index(fields=['temperature'], name='События_tempera_ebb299_idx'), models.Index(fields=['humidity'], name='События_humidit_fc26b0_idx')],
            },
        ),
    ]
