# Generated by Django 4.2.24 on 2025-09-28 06:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Дата и время создания события"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="humidity",
            field=models.FloatField(
                blank=True,
                help_text="Влажность события (%), от 0 до 100, может быть пустой",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(
                help_text="ID события, автоинкремент", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                help_text="Название события",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название события может содержать только русские и латинские буквы, цифры, '_', и N/A.",
                        regex="^([а-яА-Яa-zA-Z0-9_]+|N/A)?$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="sensor_id",
            field=models.ForeignKey(
                help_text="Сенсор, которому принадлежит событие",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="sensors.sensor",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="temperature",
            field=models.FloatField(
                blank=True,
                help_text="Температура события (°C), от -273.15 до 5499.0, может быть пустой",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-273.15),
                    django.core.validators.MaxValueValidator(5499.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="id",
            field=models.IntegerField(
                help_text="ID сенсора, целое положительное число",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(
                help_text="Название сенсора, только буквы, цифры, '-' и '/'",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Имя датчика может содержать только русские и латинские буквы, цифры, тире и слеш",
                        regex="^[а-яА-Яa-zA-Z0-9\\-/]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="type",
            field=models.IntegerField(
                help_text="Тип сенсора: целое число от 1 до 3",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
