# Generated by Django 4.2.24 on 2025-09-28 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_alter_event_created_at_alter_event_humidity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Название события",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название события может содержать только русские и латинские буквы, цифры, '_', и N/A.",
                        regex="^([а-яА-Яa-zA-Z0-9_]+|N/A)?$",
                    )
                ],
            ),
        ),
    ]
